
export const startScoreStorage: any = {
  art1 : {result: 0, question: 0}, 
  art2 : {result: 0, question: 0}, 
  art3 : {result: 0, question: 0}, 
  art4 : {result: 0, question: 0}, 
  art5 : {result: 0, question: 0}, 
  art6 : {result: 0, question: 0}, 
  art7 : {result: 0, question: 0}, 
  art8 : {result: 0, question: 0}, 
  art9 : {result: 0, question: 0}, 
  art10 : {result: 0, question: 0}, 
  art11 : {result: 0, question: 0}, 
  art12 : {result: 0, question: 0}, 
  pic1 : {result: 0, question: 0}, 
  pic2 : {result: 0, question: 0}, 
  pic3 : {result: 0, question: 0}, 
  pic4 : {result: 0, question: 0}, 
  pic5 : {result: 0, question: 0}, 
  pic6 : {result: 0, question: 0}, 
  pic7 : {result: 0, question: 0}, 
  pic8 : {result: 0, question: 0}, 
  pic9 : {result: 0, question: 0}, 
  pic10 : {result: 0, question: 0}, 
  pic11 : {result: 0, question: 0}, 
  pic12 : {result: 0, question: 0}, 
}
export const startSettingStorage = {
  help: true,
  volume: true,
  timer: true,
  time: 30,
}